/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forkjoinframework;

/**
 *
 * @author ASORTEGA
 */
public class ForkJoinFramework {

    //EL FORK JOIN FRAMEWORK DA MAS EFICIENCIA CUANDO SE TRATA DE THREADING
    //MODERN SISTEMS CAINTAIN MULTIPLE CPUS 
    //EL PARALELISMO ES EL USO DE MULTIPLES CPUS
    
    //PARALELISMO
    /*
    DIVIDE Y VENCERAS: UNA TAREA DEBERIA SER DIVIDIDA EN SUBTAREAS,
    SE DEBEN INDENTIFICAR ESAS TAREAS QUE PUEDEN SE EJECUTADAS EN PARALELO
    ALGUNOS PROBLEMAS PUEDEN SER DIFICILES DE EJECUTAR COMO TAREAS PARALELAS
    ALGUNAS PROBLEMAS SON MAS SENCILLOS: SERVIDORES QUE SOPORTAN VARIOS CLIENTES PUEDEN
    USAR TAREAS SEPARADAS PARA MANEJAR CADA CIENTE
    ORGANIZANDO MUCHAS TAREAS PARALELAS PUEDE NEGATIVAMENTE DAÑAR EL RENDIMIENTO.
    */
    
    //QUE LOS CPU SEAN DIVIDIDOS IGUALES EJ. 250000, NO QUIERE DECIR QUE TARDEN LO MISMO
    //UNOS PUEDEN SER MAR RAPIDOS QUE OTROS
    
    
}
